### ISSUE TITLE
AttributeError: GPTNeoForCausalLM has no attribute `gpt_neox`

### ISSUE THREAD

**Issue by gongye19** [yjang43/lora-multitask#1]
I get 'EleutherAI/gpt-neo-125m'  from huggingface, but target_modules were not the same.
==========================EleutherAI/gpt-neo-125m==============================
['transformer.h.0.attn.attention', 'transformer.h.0.attn.attention.attn_dropout', 'transformer.h.0.attn.attention.resid_dropout', 'transformer.h.0.attn.attention.k_proj', 'transformer.h.0.attn.attention.v_proj', 'transformer.h.0.attn.attention.q_proj', 'transformer.h.0.attn.attention.out_proj', 'transformer.h.1.attn.attention', 'transformer.h.1.attn.attention.attn_dropout', 'transformer.h.1.attn.attention.resid_dropout', 'transformer.h.1.attn.attention.k_proj', 'transformer.h.1.attn.attention.v_proj', 'transformer.h.1.attn.attention.q_proj', 'transformer.h.1.attn.attention.out_proj', 'transformer.h.2.attn.attention', 'transformer.h.2.attn.attention.attn_dropout', 'transformer.h.2.attn.attention.resid_dropout', 'transformer.h.2.attn.attention.k_proj', 'transformer.h.2.attn.attention.v_proj', 'transformer.h.2.attn.attention.q_proj', 'transformer.h.2.attn.attention.out_proj', 'transformer.h.3.attn.attention', 'transformer.h.3.attn.attention.attn_dropout', 'transformer.h.3.attn.attention.resid_dropout', 'transformer.h.3.attn.attention.k_proj', 'transformer.h.3.attn.attention.v_proj', 'transformer.h.3.attn.attention.q_proj', 'transformer.h.3.attn.attention.out_proj', 'transformer.h.4.attn.attention', 'transformer.h.4.attn.attention.attn_dropout', 'transformer.h.4.attn.attention.resid_dropout', 'transformer.h.4.attn.attention.k_proj', 'transformer.h.4.attn.attention.v_proj', 'transformer.h.4.attn.attention.q_proj', 'transformer.h.4.attn.attention.out_proj', 'transformer.h.5.attn.attention', 'transformer.h.5.attn.attention.attn_dropout', 'transformer.h.5.attn.attention.resid_dropout', 'transformer.h.5.attn.attention.k_proj', 'transformer.h.5.attn.attention.v_proj', 'transformer.h.5.attn.attention.q_proj', 'transformer.h.5.attn.attention.out_proj', 'transformer.h.6.attn.attention', 'transformer.h.6.attn.attention.attn_dropout', 'transformer.h.6.attn.attention.resid_dropout', 'transformer.h.6.attn.attention.k_proj', 'transformer.h.6.attn.attention.v_proj', 'transformer.h.6.attn.attention.q_proj', 'transformer.h.6.attn.attention.out_proj', 'transformer.h.7.attn.attention', 'transformer.h.7.attn.attention.attn_dropout', 'transformer.h.7.attn.attention.resid_dropout', 'transformer.h.7.attn.attention.k_proj', 'transformer.h.7.attn.attention.v_proj', 'transformer.h.7.attn.attention.q_proj', 'transformer.h.7.attn.attention.out_proj', 'transformer.h.8.attn.attention', 'transformer.h.8.attn.attention.attn_dropout', 'transformer.h.8.attn.attention.resid_dropout', 'transformer.h.8.attn.attention.k_proj', 'transformer.h.8.attn.attention.v_proj', 'transformer.h.8.attn.attention.q_proj', 'transformer.h.8.attn.attention.out_proj', 'transformer.h.9.attn.attention', 'transformer.h.9.attn.attention.attn_dropout', 'transformer.h.9.attn.attention.resid_dropout', 'transformer.h.9.attn.attention.k_proj', 'transformer.h.9.attn.attention.v_proj', 'transformer.h.9.attn.attention.q_proj', 'transformer.h.9.attn.attention.out_proj', 'transformer.h.10.attn.attention', 'transformer.h.10.attn.attention.attn_dropout', 'transformer.h.10.attn.attention.resid_dropout', 'transformer.h.10.attn.attention.k_proj', 'transformer.h.10.attn.attention.v_proj', 'transformer.h.10.attn.attention.q_proj', 'transformer.h.10.attn.attention.out_proj', 'transformer.h.11.attn.attention', 'transformer.h.11.attn.attention.attn_dropout', 'transformer.h.11.attn.attention.resid_dropout', 'transformer.h.11.attn.attention.k_proj', 'transformer.h.11.attn.attention.v_proj', 'transformer.h.11.attn.attention.q_proj', 'transformer.h.11.attn.attention.out_proj']
===================================Given======================================
['gpt_neox.layers.0.attention.query_key_value', 'gpt_neox.layers.1.attention.query_key_value', 'gpt_neox.layers.2.attention.query_key_value', 'gpt_neox.layers.3.attention.query_key_value', 'gpt_neox.layers.4.attention.query_key_value', 'gpt_neox.layers.5.attention.query_key_value', 'gpt_neox.layers.6.attention.query_key_value', 'gpt_neox.layers.7.attention.query_key_value', 'gpt_neox.layers.8.attention.query_key_value', 'gpt_neox.layers.9.attention.query_key_value', 'gpt_neox.layers.10.attention.query_key_value', 'gpt_neox.layers.11.attention.query_key_value', 'gpt_neox.layers.12.attention.query_key_value', 'gpt_neox.layers.13.attention.query_key_value', 'gpt_neox.layers.14.attention.query_key_value', 'gpt_neox.layers.15.attention.query_key_value', 'gpt_neox.layers.16.attention.query_key_value', 'gpt_neox.layers.17.attention.query_key_value', 'gpt_neox.layers.18.attention.query_key_value', 'gpt_neox.layers.19.attention.query_key_value', 'gpt_neox.layers.20.attention.query_key_value', 'gpt_neox.layers.21.attention.query_key_value', 'gpt_neox.layers.22.attention.query_key_value', 'gpt_neox.layers.23.attention.query_key_value']

**Comment by yjang43** [comment]
@gongye19 Thank you for your interest 😺 
It is odd to me as I remember at some point in time the module names for the gpt neox were different from the modules names of other language models.
I mainly ran the code for 6B. Maybe the module names for that one are different? idk.

I think the quick fix is to replace `target_modules.txt` with the currently-correct module names.
```
transformer.h.0.attn.attention.k_proj
transformer.h.0.attn.attention.q_proj
transformer.h.0.attn.attention.v_proj
...
transformer.h.N.attn.attention.k_proj
transformer.h.N.attn.attention.q_proj
transformer.h.N.attn.attention.v_proj
```

I checked the script running on a CPU.
